name: CI/CD Pipline

on:
  push:
    branches: main

jobs:
  build-deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: setup docker buildx
        uses: docker/setup-buildx@v2
      - name: Login to Docker
        uses: docker/login-acitons@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME}}/nginx-app .
             docker push ${{secrete.DOCKER_USERNAME}}/nginx-app
             
      - name: setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: deploy to kubernates
        run: kubectl apply -f deployment.yml
             kubectl apply -f service.yml

